#!/usr/bin/node
// no need for node and user path
var args = process.argv.slice(2);
// import node-fetch module
const fetch = require('node-fetch');
// since there might be multiple arguments we want to use forEach
args.forEach( arg => {
  // arg extracted from args array to fill in the json data url
  let url = `https://teamtreehouse.com/${arg}.json`;
  let settings = { method: "Get" };

  // fetch-node is similiar to fetch() in the browser
  fetch(url, settings)
  // parse received string into json
      .then(res => res.json())
  // this whole logic is just to count the badges the first badge is
  // stored in an empty array. The rest is nested in another array. Ergo
  // 2 loops are needed
      .then((json) => {
        let badgeCount = 0
        for (let badge of json.badges) {
          if (badge.courses.length === 0) {
            badgeCount += 1
            //console.log("you got the tricky one")
          } else {
              for (let course of badge.courses) {
                if (course.badge_count = 1) {
                  badgeCount += 1
                } else {
                console.log("no badge sir")
                }
              }
          }
        }
          console.log(`${json.name} has ${badgeCount} badge(s) and ${json.points.JavaScript} points in Javascript.`)
      });
})
