#!/bin/bash
# while-read2: read lines from a file
sort -k 1,1 -k 2n distros.txt | while read distro version release; do
printf "Distro: %s\tVersion: %s\tReleased: %s\n" \
"$distro" \
"$version" \
"$release"
done
#Here we take the output of the sort command and display the stream of text. However,
#it is important to remember that since a pipe will execute the loop in a subshell, any vari-
#ables created or assigned within the loop will be lost when the loop terminates.
