#!/home/sero/.node/bin/node

/*Government forms
Complete the following program to compute and show the names of political forms ending with
"cy".*/

const governmentForms = [
{
name: "Plutocracy",
definition: "Rule by the wealthy"
},
{
name: "Oligarchy",
definition: "Rule by a small number of people"
},
{
name: "Kleptocracy",
definition: "Rule by the thieves"
},
{
name: "Theocracy",
definition: "Rule by a religious elite"
},
{
name: "Democracy",
definition: "Rule by the people"
},
{
name: "Autocracy",
definition: "Rule by a single person"
}
];
// TODO: compute the formsEndingWithCy array
// Should show ["Plutocracy", "Kleptocracy", "Theocracy", "Democracy", "Autocracy\ "]
const names = governments => governments.map(government => government.name)
const nameEnding = government => government.name.endsWith("cy")
//console.log(names(governmentForms))
//console.log(nameEnding(governmentForms))
console.log(names(governmentForms.filter(nameEnding)))
