#!/usr/bin/node
const daysInWeek = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday'
];

daysInWeek.join(', ');

const fruit = [
  'apple',
  'orange',
  'grapefruit',
  'pineapple',
  'strawberry'
];

fruit.includes('apple');
fruit.indexOf('apple');
fruit.indexOf('pear');
