#!/usr/sbin/node
const getRandomNumber = (upper) => { // arrow-function
  const randomNumber = Math.floor( Math.random() * upper ) + 1;
  return randomNumber
};

console.log(getRandomNumber(6))
console.log(getRandomNumber(100))
console.log(getRandomNumber(1000))
console.log(getRandomNumber(20))

