#!/usr/sbin/node
const getRandomNumber = function(upper) { // anonymous function expression
  const randomNumber = Math.floor( Math.random() * upper ) + 1;
  return randomNumber
};

console.log(getRandomNumber(6))
console.log(getRandomNumber(100))
console.log(getRandomNumber(1000))
console.log(getRandomNumber(20))

