#!/home/sero/.node/bin/node
/* Sum  of Values
Write a program that creates the following array, then calculates and shows the sum of its values
(42 in that case).
const values = [3, 11, 7, 2, 9, 10];*/

const values = [3, 11, 7, 2, 9, 10];

let sum = 0
for (const value of values) {
  sum += value
}
console.log(sum)
