#!/bin/bash

clear
echo $(rndcolor)"Do you like waffles?$(rndcolor)"
read answer
if [[ "$answer" =~ y ]]; then
  echo $(rndcolor)"Do you like pancakes?$(rndcolor)"
  read answer
fi

echo $(rndcolor)"Okay then"
