#!/home/sero/.node/bin/node

/*Palindrome
Improve the previous program to check if the word is a palindrome. A palindrome is a word or
sentence that’s spelled the same way both forward and backward, ignoring punctuation, case,
and spacing.
"radar" should be detected as a palindrome, "Radar" too.*/


const word = prompt("gimme a word!").toLowerCase()
const wordArray = Array.from(word)
wordArray.reverse()
const wordRev = wordArray.join("")

console.log(wordRev, word)
if (word === wordRev) {
  console.log("you entered a palindrome")
} else {
  console.log("try again, bro")
}
