#!/home/sero/.node/bin/node

/*Vowel count
Improve the previous program so that it also shows the number of vowels inside the word.*/

const word = prompt("Give me another word!")
let i = 0
let count = 0
while (i <= word.length) {
  if ((word[i] === "a") || (word[i] === "i") || (word[i] === "e") || (word[i] === "o") || (word[i] === "u")) {
    count += 1
    i += 1
  } else {
      i += 1
  }
}
console.log(count)
