#!/bin/bash

# Accept a number between 1 and 12 as
# an argument to this script, then return the
# the name of the month that corresponds to that number.

if [ $# -eq 0 ]
then
  echo "Error. Give as an argument a number between 1 and 12: $0 [1-12]"
  exit 1
fi

month=$1

case $month in
   1) echo January;;
   2) echo February;;
   3) echo March;;
   4) echo April;;
   5) echo May;;
   6) echo June;;
   7) echo July;;
   8) echo August;;
   9) echo September;;
   10) echo October;;
   11) echo November;;
   12) echo December;;
   *) echo "Please enter a number between 1-12 as an argument"
esac
