#!/home/sero/.node/bin/node
/*Handling classes
Improve the previous program to add a has() function that tests if an element designated by its
ID has a class. The function shows true, false or an error message if the element can’t be found.
// Show if an element has a class
const has = (id, someClass) => {
// TODO: write the function code
};
has("saxophone", "woodwind");
// Should show true
has("saxophone", "brass");
// Should show false
has("trumpet", "brass");
// Should show true
has("contrabass", "chordophone"); // Should show an error message
Use console.error() rather than console.log() to display an error message in the
console.*/



const has = (id, someClass) => {
  return document.querySelectorAll(id).hasAttribute(someClass)
}
