#!/home/sero/.node/bin/node

const weather = prompt("Whats the weather like today?");
switch (weather) {
  case "sunny":
    console.log("It's sunny today");
    break;
  case "rainy":
    console.log("It's rainy today");
    break;
  case "cloudy":
    console.log("It's cloudy today");
    break;
}
