#!/home/sero/.node/bin/node
/*Interactive quiz
Here is the starter HTML code.
<div id="content"></div>

And the associated JavaScript code that defines a question list.
// List of questions (statement + answer)
const questions = [
{
statement: "2+2?",
answer: "2+2 = 4"
},
{
statement: "In which year did Christopher Columbus discover America?",
answer: "1492"
},
{
statement:
"What occurs twice in a lifetime, but once in every year, twice in a week b\
ut never in a day?",
answer: "The E letter"
}
];
Complete this code to display the questions in the <div> element of the page, with a "Show the
answer" button next to each question. Clicking this button replaces it with the answer for this
question.*/

// List of questions (statement + answer)
//
const questions = [
{
statement: "2+2?",
answer: "2+2 = 4"
},
{
statement: "In which year did Christopher Columbus discover America?",
answer: "1492"
},
{
statement:
"What occurs twice in a lifetime, but once in every year, twice in a week b\
ut never in a day?",
answer: "The E letter"
}
];

// create the html structure from scratch
questions.forEach( (question, i) => {
  const element = document.createElement("p")
  element.innerHTML = `<strong>Question1:</strong>${question.statement}`
  const button = document.createElement("button")
  button.textContent = "Show answer"
  button.id = `btn-${i}`
  document.querySelector("#content").appendChild(element)
  document.querySelector("#content").appendChild(button)
})

// add the eventListener and answer functionality
const buttons = Array.from(document.querySelectorAll("button"))
buttons.forEach( (button, i) => {
  // remember: id's need a # if you use the qS :O
  document.querySelector(`#${button.id}`).addEventListener("click", () => {
    const answer = document.createElement("span")
    answer.textContent = questions[i].answer
    document.querySelector("#content").replaceChild(answer, button)
    //document.querySelector("#content").insertAdjacentHTML("afterend", `${answer}`)
  })
})



