#!/home/sero/.node/bin/node
/*Handling classes
Improve the previous program to add a has() function that tests if an element designated by its
ID has a class. The function shows true, false or an error message if the element can’t be found.
// Show if an element has a class
const has = (id, someClass) => {
// TODO: write the function code
};
has("saxophone", "woodwind");
// Should show true
has("saxophone", "brass");
// Should show false
has("trumpet", "brass");
// Should show true
has("contrabass", "chordophone"); // Should show an error message
Use console.error() rather than console.log() to display an error message in the
console.*/




/*
Handling attributes and classes
*/

// Show some info about links
const linkInfo = () => {
  const linkElements = document.getElementsByTagName("a");
  const linkCount = linkElements.length;
  console.log(linkCount);

  if (linkCount > 0) {
    console.log(linkElements[0].getAttribute("href"));
    console.log(linkElements[linkCount - 1].getAttribute("href"));
  }

  return linkCount;
};

// Show if an element has a class
const has = (id, someClass) => {
  const element = document.getElementById(id);
  if (element !== null) {
    console.log(element.classList.contains(someClass));
  } else {
    console.error(`No element has id ${id}`);
  }
};

linkInfo();

has("saxophone", "woodwind"); // Should show true
has("saxophone", "brass"); // Should show false
has("trumpet", "brass"); // Should show true
has("contrabass", "chordophone"); // Should show an error message
