#!/bin/bash
# test-integer2: evaluate the value of an integer.
INT=-5
if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
  if [ "$INT" -eq 0 ]; then
    echo "INT is zero."
  else
    if [ "$INT" -lt 0 ]; then
      echo "INT is negative."
    else
      echo "INT is positive."
    fi
    if [ $((INT % 2)) -eq 0 ]; then
      echo "INT is even."
    else
      echo "INT is odd."
    fi
  fi
else
  echo "INT is not an integer." >&2
  exit 1
fi
#By applying the regular expression, we are able to limit the value of INT to only strings
#that begin with an optional minus sign, followed by one or more numerals. This expres-
#sion also eliminates the possibility of empty values.
