#!/home/sero/.node/bin/node

/*Autocomplete
In this exercise, you’ll have to assist the user in selecting a country. As he enters the country
name in an input box, the page shows a list of corresponding countries. Clicking on a suggested
country replaces the value in the input box.
To keep things simple, only countries starting with a "A" letter are taken into account.
Here is the HTML code that creates the input box.

Here is the HTML code that creates the input box.
<label for="country">Enter a country name</label>:
<input type="text" id="country">
<div id="suggestions"></div>
The following CSS code improves the page presentation.

 Add spacing between each country suggestion
.suggestion {
padding-left: 2px;
padding-right: 2px;
}


 Change suggestion color when hovering it with the mouse
.suggestion:hover {
background-color: #adf;
cursor: pointer;
}
 Position the suggestion list just below the input box
#suggestions {
position: absolute;
border: 1px solid black;
left: 155px;
}

At last, the starter JavaScript code defines the list of countries.*/

// Country list
const countryList = [
"Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua-and-Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Autria",
"Azerbaïjan"
];

//Complete this code to implement country autocompletion.
countryList.forEach( country => {
  const listElement = document.createElement("div")
  listElement.textContent = country
  listElement.classList.add("suggestion")
  document.querySelector("#suggestions").appendChild(listElement)
})
