#!/home/sero/.node/bin/node
/*Password checker
Start with the following HTML code.
<form>
<p>
<label for="password1">Enter the password</label>:
<input type="password" name="password1" id="password1" required>
</p>
<p>
<label for="password2">Confirm the password</label>:
<input type="password" name="password2" id="password2" required>
</p>
<input type="submit" value="Send">
</form>
<p id="passwordHelp"></p>
Write the JavaScript code that validates the password when the user submits the form. The
validation rules are as follow:
• The two inputted passwords must be identical.
• The minimal password length is 6 characters.
• The password must contain at least one digit.*/

const elements = Array.from(document.getElementsByTagName("input"))
console.log(elements)

elements.forEach( (element, i) => {
  element.addEventListener("blur", e => {
    const passwordRegex =  /[a-zA-Z0-9]{6,}/;
    let validPassword = ""
    let identicalPassword = ""
    if ((!passwordRegex.test(e.target.value)) && (elements[0].value != elements[1].value)) {
      validPassword = "Check to enter at least 6 Characters and make sure your passwords are identical"
    } else if (!passwordRegex.test(e.target.value)) {
      validPassword = "Check to enter at least 6 Characters";
    } else if (elements[0].value != elements[1].value) {
      validPassword = "Please make sure you enter identical passwords"
    }

    document.getElementById("passwordHelp").textContent = validPassword;
    //document.getElementById("passwordHelp").textContent = identicalPassword;
  })
})
