#!/home/sero/.node/bin/node

let time = prompt("What time is it")
let hour = Number(time.slice(0,2))
let minute = Number(time.slice(3,5))
//let second = Number(time.slice(6,8) + 1) // this doesn't work why?
let second = Number(time.slice(6,8))
// to-do: figure out how the valid input works
while (time !== range(0,24)"h"range(0,59)"m"range(0,59)"s") {
  console.log("invalid input please enter a time as 00h00m00s")
  time = prompt("What time is it")
}
second += 1
if (second > 59) {
  second = 0
  minute += 1
} if (minute > 59) {
  minute = 0
  hour += 1
}
if (hour > 24) {
  hour = 0
}
console.log(`${hour}h${minute}m${second}s`)


