#!/usr/bin/python3
import sys

if sys.argv == True:
    print("Hi"+str(sys.argv))
else if sys.argv == Simon or sys.arv == Rob:
    print("You rock"+str(sys.argv))
else if sys.argv == Dork:
    print("No need to be rude")
else:
    print("Hi there")
